isDev: false
output:
  directory: "./output/"
queries:
  kanto:
    # tokyo
    13: 102,104,113,101,103,105,107,108,121,122,123,106,118,109,110,111,112,120,114,115,116,117,119,201,202,203,208,209,213,215,224,229,204,206,207,210,211,212,214,218,219,221,222,223,225,227
    # kanagawa
    14: 135,137,131,132,133,134,136,102,109,113,117,118,101,104,106,112,114,105,107,108,110,111,115,153,151,152,211,212,213,215,216,203,205,201,204,207
    # chiba
    12: 103,102,101,104,106,227,204,203,216,221,212,207,217,224,220,222,231,232,211
    # saitama
    11: 214,222,237,221,232,234,240,243,103,102,108,203,104,105,106,107,109,223,224,231,217,219,233,201,208,227,235,239,241,245,215,225,229,230,242
    # ibaraki
    8: 208,217,219,220
